server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Route to Student Service
        - id: student_route
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/fetch-students/**
          filters:
            - name: SetStatus
              args:
                status: 200   # Always respond with 200 (example)
            - AddResponseHeader=X-Service, StudentService

        # Route to School Service
        - id: school_route
          uri: lb://SCHOOL-SERVICE #lb is loadbalanced
          predicates:
            - Path=/school/**
          filters:
            - name: SetStatus
              args:
                status: 401   # Return "Unauthorized" response for testing
            - AddResponseHeader=X-Service, SchoolService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
